// English Translations
// ignore_for_file: file_names

const Map<String, String> enUS = {
  'Languages': 'Languages',
  'Language': 'Language',
  'Meul Keila': 'Meul Keila',
  'Matches': 'Matches',
  'Live': 'Live',
  'News': 'News',
  'Standings': 'Standings',
  'More': 'More',
  'Log Out': 'Log Out',
  'Theme': 'Theme',
  'Visit': 'Visit',
  'Facebook': 'Facebook',
  'Telegram': 'Telegram',
  'YouTube': 'YouTube',
  'Support': 'Support',
  'Invite Friends': 'Invite Friends',
  'Rate & Review': 'Rate & Review',
  'Check for updates': 'Check for updates',
  'Privacy Policy':
      'Privacy Policy',
  'Select Theme': 'Select Theme',
  'Close': 'Close',
  'Select Language': 'Select Language',
  'Search for league': 'Search for league',
  'No match is live now, Try after sometime. \n Thanks!': 'No match is live now, Try after sometime. \n Thanks!',
  'No Completed matches, When any match will be complted,it will show here.':
      'No Completed matches, When any match will be complted,it will show here.',
  'Server Error! Please Try again.': 'Server Error! Please Try again.',
  'No internet connection please try again!': 'No internet connection please try again!',
  'Get started with': 'Get started with',
  "Add your phone number. we'll send you a verification code so we know you're real": "Add your phone number. we'll send you a verification code so we know you're real",
  'Type 6 digit code sent to this number': 'Type 6 digit code sent to this number',
  'Confirm Phone Number': 'Confirm Phone Number',
  "Didn't receive any code?": "Didn't receive any code?",
  'Resend again':
      'Resend again',
  'Verify': 'Verify',
  'Complete Profile': 'Complete Profile',
  'Enter your name and email to complete your profile setup': 'Enter your name and email to complete your profile setup',
  'Please enter your full name': 'Please enter your full name',
  'Full Name': 'Full Name',
  'Email Address': 'Email Address',
  'Complete': 'Complete',
  'Send': 'Send',
  'WATCH LIVE':
      'WATCH LIVE',
  'Refresh': 'Refresh',
  'News Details': 'News Details',
  'Live Match': 'Live Match',
  'Full Time':
      'Full Time',
  'Line-Ups': 'Line-Ups',
  'Statistics': 'Statistics',
  'No Player List': 'No Player List',
  'No Commentary available for this match': 'No Commentary available for this match',
  'Key Commentary':
      'Key Commentary',
  'No Statistics report available':
      'No Statistics report available',
  'No data available for this match!': 'No data available for this match!',
  'Head To Head': 'Head To Head',
  'Top Scorers': 'Top Scorers',
  'Most Assists': 'Most Assists',
  'This link is not playable,Try another one': 'This link is not playable,Try another one',
  'Information': 'Information',
  'Commentary': 'Commentary',
  'No Player available': 'No Player available',
  'Chats': 'Chats',
  'Send a message ...': 'Send a message ...',
  'No Leagues found!': 'No Leagues found!',
  'Please enter phone number': 'Please enter phone number',
  ' Type 6 digit code sent to this number ': ' Type 6 digit code sent to this number ',
  'Please enter full OTP code': 'Please enter full OTP code',
  'No prediction available.': 'No prediction available.',
  'Prediction': 'Prediction',
  'Resend code in:': 'Resend code in:',
  'Enter your name to complete your profile setup': 'Enter your name to complete your profile setup',
  'Tab For Details': 'Tab For Details',
};
