// Spanish Translations
// ignore_for_file: file_names

const Map<String, String> viVI = {
  'Languages': 'Ngôn ngữ',
  'Language': 'Ngôn ngữ',
  'Meul Keila': 'BÓNG ĐÁ LIVE K9',
  'Live': 'Trực tiếp',
  'News': 'Tin tức',
  'Home': 'Trang Chủ',
  'Standings': 'Bảng xếp hạng',
  'More': 'Thêm',
  'Log Out': 'Đăng xuất',
  'Theme': 'Chủ đề',
  'Visit': 'Ghé thăm',
  'Completed': 'Hoàn thành',
  'Facebook': 'Facebook',
  'ALL': 'Tất cả các',
  'On Going': 'Đang diễn ra',
  'Password': 'Contraseña',
  'Telegram': 'Telegram',
  'YouTube': 'YouTube',
  'Support': 'Hỗ trợ',
  'Invite Friends': 'Mời bạn bè',
  'Rate & Review': 'Đánh giá tỉ lệ',
  'Check for updates': 'Kiểm tra cập nhật',
  'Privacy Policy': 'Chính sách bảo mật',
  'Select Theme': 'Lựa chọn chủ đề',
  'Close': 'Đóng',
  'Select Language': 'Chọn ngôn ngữ',
  'Search for league': 'Tìm kiếm giải đấu',
  'No match is live now, Try after sometime. \n Thanks!':
      'Hiện tại chưa có trận đấu phát trực tiếp nào, Hãy thử lại sau. Cảm ơn!',
  'No Completed matches, When any match will be complted,it will show here.':
      'Chưa có trận đấu nào trước đó và sẽ hiển thị ở đây khi trận đấu kết thúc.',
  'Server Error! Please Try again.': 'Lỗi máy chủ! Vui lòng thử lại.',
  'No internet connection please try again!':
      'Không có kết nối internet, vui lòng thử lại! ',
  'Get started with': 'Bắt đầu với',
  'Add your phone number. we\'ll send you a verification code so we know you\'re real':
      'Thêm số điện thoại của bạn. chúng tôi sẽ gửi cho bạn mã xác minh để chúng tôi biết đó là số của bạn.',
  'Type 6 digit code sent to this number':
      'Nhập mã 6 chữ số được gửi đến số này',
  'Confirm Phone Number': 'Xác nhận số điện thoại',
  'Didn\'t receive any code?': 'Không nhận được bất kỳ mã nào?',
  'Resend again': 'Gửi lại lần nữa',
  'Complete Profile': 'Hoàn thành hồ sơ',
  'Enter your name and email to complete your profile setup':
      'Nhập tên và email của bạn để hoàn tất thiết lập hồ sơ của bạn',
  'Please enter your full name': 'Vui lòng nhập tên đầy đủ của bạn',
  'Full Name': 'Họ và tên',
  'Email Address': 'Địa chỉ email',
  'Complete': 'Hoàn thành hồ sơ',
  'Send': 'Gửi',
  'WATCH LIVE': 'XEM TRỰC TIẾP',
  'Refresh': 'Làm mới',
  'News Details': 'Chi tiết Tin tức',
  'Live Match': 'Trận đấu trực tiếp',
  'Full Time': 'Toàn thời gian',
  'Line-Ups': 'Xếp hàng',
  'Contact Us': 'Contáctenos',
  'Statistics': 'Statistics',
  'No Player List': 'Không có danh sách người chơi',
  'No Commentary available for this match':
      'Không có bình luận nào cho trận đấu này',
  'Key Commentarys': 'Bình luận chính',
  'No Statistics report available': 'Không có báo cáo thống kê',
  'No data available for this match!': 'Không có sẵn dữ liệu cho trận đấu này!',
  'Head To Head': 'Đối đầu',
  'Top Scorers': 'Người ghi bàn hàng đầu',
  'Most Assists': 'Hỗ trợ nhiều nhất',
  'This link is not playable,Try another one':
      'Không thể mở liên kết này. Hãy thử một liên kết khác',
  'Information': 'Thông tin',
  'Commentary': 'Bình luận chính',
  'No Player available': 'Không có người chơi',
  'Chats': 'Chats',
  'Send a message ...': 'Gửi tin nhắn ...',
  'No Leagues found!': 'Không tìm thấy Giải đấu nào!',
  'Please enter phone number': 'Vui lòng nhập số điện thoại',
  'Please enter full OTP code': 'Vui lòng nhập mã OTP đầy đủ',
  'No prediction available.': 'Không có dự đoán nào.',
  'Prediction': 'Dự đoán',
  'Resend code in:': 'Gửi lại mã trong:',
  'Enter your name to complete your profile setup':
      'Nhập tên của bạn để hoàn thành hồ sơ',
  'Tab For Details': 'Bấm vào để xem chi tiết',
};
